steps:
  - id: Initiate gcloud
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      [
        "/workspace/cloudbuild/scripts/gcloud_config.sh",
        "${PROJECT_ID}",
        "${LOCATION}",
      ]
  - id: Build and deploy functions
    name: node:22-alpine
    entrypoint: sh
    args:
      [
        "/workspace/cloudbuild/scripts/build_deploy.sh",
        "${PROJECT_ID}",
        "${_SERVICE_ACCOUNT}",
        "production",
        "${PROJECT_NUMBER}",
      ]
timeout: 1000s
logsBucket: gs://blackpaw-build-logs/cloud-functions
